---
title:  "SPAM2005v3r0 Global Maps"
author: "IFPRI"
date:   "December, 2015. Last updated on `r Sys.Date()`. DRAFT, do not use or cite."
output:
  html_document:
    fig_height: 5
    toc: true
    toc_float: true    
    fig_caption: true  
---


```{r setup}

library(data.table)
library(raster)
library(rbokeh)
library(tmap)

load("./tmp/SPAM2005v3r0.RData")

```


```{r data, eval=F}

setwd("~/Projects/hc-shiny")

# Load SPAM data and metadata
load("../hc-data/SPAM/2005v3r0/rds/SPAM2005V3r0_global.rda")
load("../hc-data/SPAM/2005v3r0/rds/vi.rda")

# Keep a few variables
spam <- spam[, .SD, .SDcols=1:20]

save.image("./SPAM/tmp/SPAM2005v3r0.RData")

```


```{r}

tmp <- SpatialPixelsDataFrame(spam[, .(X,Y)], data.frame(spam),
  proj4string=CRS("+init=epsg:4326"))

var <- "maiz_a_ta"
tmp <- raster(tmp, layer=var)

data(World)
setkey(vi, varCode)
tmp[tmp==0] <- NA
xy <- coordinates(tmp)
tmp <- as.matrix(tmp)


# Hexbin plot
figure() %>% ly_hexbin(rnorm(10000), rnorm(10000))

figure(xgrid=F, ygrid=F, width=630, height=540,
  xlab="Horizontal distance from home plate (ft.)",
  ylab="Vertical distance from home plate (ft.)") %>%
  ly_hexbin(doubles, xbins=50, shape=0.77, alpha=0.75, palette="Spectral10")

# Raster plot
figure(title=vi[var, varTitle], padding_factor=0) %>%
  ly_image(as.matrix(tmp), x=xy[, "x"], y=xy[, "y"])
   ly_map(spTransform(World, proj4string(tmp)), color=NULL, line_color="gray")


```






